name: Synchronize Repositories

on:
  workflow_dispatch:
  push:
    branches:
      - master

jobs:
  milestone:
    name: Synchronize Repositories
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: webfactory/ssh-agent@v0.4.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          
      - name: Synchronize ORY Themes
        run: ./scripts/sync-library.sh ory/themes master Themes
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN_AENEASR }}
